version: '3'

services:
  db_blog:
    image: postgres
    container_name: db_blog
    environment:
      PGDATA: /var/lib/postgresql/pgdata
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  app_blog:
    build:
      context: .
    container_name: app_blog
    depends_on:
      db_blog:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py loaddata data2.json
      && python manage.py loaddata data1.json
      && python manage.py loaddata data.json
      && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: