# Generated by Django 4.2.5 on 2023-09-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Контент платный'),
        ),
        migrations.AddField(
            model_name='blog',
            name='payment_amount',
            field=models.IntegerField(default=0, verbose_name='Стоимость подписки'),
        ),
    ]
