# Generated by Django 4.2.5 on 2023-09-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_stripecheckoutsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCheckoutSession',
        ),
    ]
